version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: whatsapp_chat_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  app:
    build: .
    env_file:
      - .env.example
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    command: npm run dev

volumes:
  db_data:
